
server:
  port: 8801


#数据库相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://192.168.1.23:3306/wechatshop?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.142.132:3306/shop?allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: wxshop
    password: 123456
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 300MB # 单个文件大小
      max-request-size: 600MB # 连续上传文件大小



mybatis:
  mapper-locations: classpath:mapper/*.xml
  # type-aliases-package: com.wx.shop.model.entity # 所有entity别名所在包
  type-aliases-package: com.wx.shop.entities.pojo # 所有entity别名所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2-spring.xml


# 文件保存位置
savefile:
  file:
    root:
      path: "C:\\Users\\vincentEnxy\\Desktop\\Temp\\imgs\\" # 存储路径

